version: '3.8'
services:
  web:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '.:/quiz'
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - SECRET_KEY=apuvicmef^(!j8gx&clu0u(!8m0r^etok^l0)kc!---#(i5=dt
      - 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
  celery:
    build: .
    command: celery -A quiz worker -l INFO
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=1
      - SECRET_KEY=apuvicmef^(!j8gx&clu0u(!8m0r^etok^l0)kc!---#(i5=dt
      - 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A quiz beat -l info
    volumes:
      - '.:/quiz'
    environment:
      - DEBUG=1
      - SECRET_KEY=apuvicmef^(!j8gx&clu0u(!8m0r^etok^l0)kc!---#(i5=dt
      - 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
    depends_on:
      - web
      - redis
      - celery
